### ISSUE TITLE
"serve-d language server for D unable to start"

### ISSUE THREAD

**Issue by RealDoigt** [Pure-D/atom-ide-d#49] opened 2021-05-25 03:06 UTC
Also getting a code -13.
I'm on Kubuntu.

**Comment by aminya** [comment] 2021-05-25 03:37
Have you tried restarting? 

Also, try reinstalling:
```
apm uninstall ide-d
```

```
apm install ide-d
```

**Comment by RealDoigt** [comment] 2021-05-25 23:59
I did, but I hadn't tried with the commands. I'll give it a try now.

**Comment by aminya** [comment] 2021-05-26 00:24
Close all the open files, open the dev tools using `CTRL+SHIFT+I`, hide the excess messages like the following.
![image](https://user-images.githubusercontent.com/16418197/119584688-b71bf300-bd8e-11eb-829b-e18f2939da61.png)

Then report back any "error" that is related to D.

**Comment by RealDoigt** [comment] 2021-05-27 00:40
https://pastebin.com/EtQzbwQ0
https://pastebin.com/3UCbwgzM
https://pastebin.com/brKu10pZ
https://imgur.com/a/wbBg7kN

**Comment by aminya** [comment] 2021-05-27 00:49
Please try deleting this folder and install again: `/home/doigt/.local/share/code-d` (have a backup)

`serve-d` is not spawned due to `EACCES` error!

@WebFreak001 Does `serve-d` require any special permission for spawning?

**Comment by RealDoigt** [comment] 2021-05-27 00:59
The situation didn't change.

**Comment by aminya** [comment] 2021-05-27 01:01
Could you run `ls` inside `/home/doigt/.local/share/code-d`? Maybe upload the folder as a zip so we can try it ourselves.

**Comment by RealDoigt** [comment] 2021-05-27 01:05
there's only one folder in there and it's bin. Within bin there are 3 files;
dcd-client
dcd-server
serve-d
[code-d.zip](https://github.com/Pure-D/atom-ide-d/files/6550423/code-d.zip)

**Comment by WebFreak001** [comment] 2021-05-27 07:18
is serve-d marked as executable?

**Comment by aminya** [comment] 2021-05-27 07:23
When I run the uploaded `serve-d` directly, it seems to be a executable:
```d
$ /mnt/c/Users/aminy/Desktop/code-d/bin/serve-d
2021-05-27T02:22:08.603 [trace] app.d:119:main Features fulfilled
serve-d v0.7.0-beta.5 with workspace-d v3.5.0
Included features: "d", "workspaces"
Built: Thu Feb 25 09:14:23 2021
with compiler LDC v2.95 on linux littleEndian
dub, dfmt and dscanner are bundled within (compiled in)
2021-05-27T02:22:08.603 [trace] serverbase.d:269:run Started reading from stdin
2021-05-27T02:22:08.607 [trace] serverbase.d:275:run RPC started
```

**Comment by RealDoigt** [comment] 2021-05-27 12:47
> is serve-d marked as executable?

No, I'll mark it as executable and try again

**Comment by RealDoigt** [comment] 2021-05-27 12:50
Ok so the problem is each time the editor starts, the files get reinstalled and serve-d is not marked as executable each time it does. It's useless to try to mark serve-d as executable because by then it will have crashed and given up on trying to run serve-d.

**Comment by aminya** [comment] 2021-05-27 22:28
I think the issue is that I published the package from Windows, and the attributes for the executables were not saved during publishing. I need to find a way to automate the process in the CI.

**Closed** 2021-06-02 10:58 UTC
Labels: bug
